### ISSUE TITLE
Short list of key features

### ISSUE THREAD

**Issue by bedware** [zold-io/zold.github.io#106]
Pre-history:
Not every person has time to read long whitepapers. On your site I did not find any summary why zold better than Bitcoin.
![c14ccff3-d823-42e6-a45a-9a164bb25e40](https://user-images.githubusercontent.com/3441783/50908677-441eb580-143b-11e9-9937-c10ffc799235.jpeg)
Solution:
What he is talking about, I think, is the newcomers want to see the short list of these key features when they come to the zold webpage to instantly understand why they need to use it.  Because it’s not obvious to find exactly that page and it takes time.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@bedware[/z](https://www.0crat.com/u/bedware) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZUFVA8H) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@rultor release, tag is `0.11.4`

**Comment by yegor256** [comment]
@bedware done, thanks!

**Comment by 0crat** [comment]
Job `gh:zold-io/zold.github.io#106` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@df7d6e22-e79d-41ca-b6d1-a3d0a264f06b, thread: pool-195-thread-1
com.jcabi.github.RtValuePagination$Items[181] java.lang.IllegalStateException: java.io.IOException: failed after 4 attempts
com.jcabi.http.wire.RetryWire[95] java.io.IOException: failed after 4 attempts
```

[0.40.12](https://github.com/zerocracy/farm): Issue: zold-io/zold.github.io#106, Action: `created`
