### ISSUE TITLE
Blink every time we update a node

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold.github.io#11]
Let's blick the item on the list (in `#remotes`) every time we fetch the data from the node in `/map.html`, in order to show that this list is being updated in real-time mode. How exactly we will "blick" is up to the HTML designer.

**Comment by 0crat** [comment]
Job [#11](https://github.com/zold-io/zold.github.io/issues/11) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#11](https://github.com/zold-io/zold.github.io/issues/11); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@0crat assign @blackout314

**Comment by 0crat** [comment]
> @0crat assign @blackout314 ([here](https://github.com/zold-io/zold.github.io/issues/11#issuecomment-394714565))

@yegor256 The job [#11](https://github.com/zold-io/zold.github.io/issues/11) assigned to @blackout314[/z](https://www.0crat.com/u/blackout314), here is [why](https://www.0crat.com/footprint/CAZUFVA8H/1561353015); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@blackout314[/z](https://www.0crat.com/u/blackout314) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by blackout314** [comment]
@yegor256 travis need `npm start`

**Comment by 0crat** [comment]
The user @blackout314[/z](https://www.0crat.com/u/blackout314) resigned from [#11](https://github.com/zold-io/zold.github.io/issues/11), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @blackout314[/z](https://www.0crat.com/u/blackout314)

**Comment by yegor256** [comment]
@blackout314 please, report issues separately. If you see a bug in our code, please create a new ticket. Otherwise, your comments will simply be lost/ignored.

**Comment by blackout314** [comment]
@yegor256 ok i report a issue for `npm` 
this task anyway (blink) is completed

**Comment by yegor256** [comment]
@blackout314 thanks!

**Comment by yegor256** [comment]
@rultor release, tag is `0.2.0`

**Comment by 0crat** [comment]
Job `gh:zold-io/zold.github.io#11` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#11](https://github.com/zold-io/zold.github.io/issues/11) is now out of scope
