### ISSUE TITLE
show graph at the front page

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold.github.io#114]
Let's put it there.

**Comment by yegor256** [comment]
@rultor release, tag is `0.12.3`

**Comment by yegor256** [comment]
@rultor hello

**Comment by yegor256** [comment]
@rultor release, tag is `0.12.4`

**Comment by 0crat** [comment]
Job `gh:zold-io/zold.github.io#114` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
