### ISSUE TITLE
/diff.html

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold.github.io#119]
Let's add a new page to compare two versions of the wallet file

**Comment by yegor256** [comment]
@rultor release, tag is `0.13.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.13.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.13.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.13.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.13.2`

**Comment by 0crat** [comment]
Job `gh:zold-io/zold.github.io#119` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by yegor256** [comment]
@rultor release, tag is `0.13.2`

**Comment by yegor256** [comment]
@rultor release, tag is `0.13.3`
