### ISSUE TITLE
The right panel is not updated immediately

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold.github.io#12]
When I reload `/map.html` the right panel is not updated immediately, but only in 10 seconds. I believe, it's a bug.

**Comment by 0crat** [comment]
Job [#12](https://github.com/zold-io/zold.github.io/issues/12) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#12](https://github.com/zold-io/zold.github.io/issues/12); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
The job [#12](https://github.com/zold-io/zold.github.io/issues/12) assigned to @blackout314[/z](https://www.0crat.com/u/blackout314), here is [why](https://www.0crat.com/footprint/CAZUFVA8H/1641726929); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by blackout314** [comment]
@yegor256 we cant fix this, we need to cache it because is BE slow (4-5 sec for response)

**Comment by blackout314** [comment]
@yegor256 ok

**Comment by blackout314** [comment]
@yegor256 this task -> merged (closed)

**Comment by yegor256** [comment]
@blackout314 thanks!

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @blackout314[/z](https://www.0crat.com/u/blackout314), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#12](https://github.com/zold-io/zold.github.io/issues/12) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @blackout314[/z](https://www.0crat.com/u/blackout314)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
