### ISSUE TITLE
Show nodes in a table

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold.github.io#13]
Currently all nodes are listed in `#remotes` as a `<ul>`, which is not convenient to read. Let's use `<table>` instead, with four columns:

  * node address, like `b2.zold.io:4096`
  * node score
  * total number of wallets
  * version of the software

**Comment by 0crat** [comment]
Job [#13](https://github.com/zold-io/zold.github.io/issues/13) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#13](https://github.com/zold-io/zold.github.io/issues/13); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@0crat assign @blackout314

**Comment by 0crat** [comment]
> @0crat assign @blackout314 ([here](https://github.com/zold-io/zold.github.io/issues/13#issuecomment-394714478))

@yegor256 The job [#13](https://github.com/zold-io/zold.github.io/issues/13) assigned to @blackout314[/z](https://www.0crat.com/u/blackout314), here is [why](https://www.0crat.com/footprint/CAZUFVA8H/1561353012); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@blackout314[/z](https://www.0crat.com/u/blackout314) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by blackout314** [comment]
@yegor256 after fix #22 this can go online

**Comment by yegor256** [comment]
@blackout314 thanks!

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @blackout314[/z](https://www.0crat.com/u/blackout314), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#13](https://github.com/zold-io/zold.github.io/issues/13) is now out of scope

**Comment by ypshenychka** [comment]
@blackout314 Could you please confirm that this job was closed without a solution provided (as far as it was fixed in another issue)?

**Comment by ypshenychka** [comment]
@blackout314 ping

**Comment by blackout314** [comment]
@ypshenychka yes is cloed

**Comment by ypshenychka** [comment]
@blackout314 I mean that no solution was provided directly in this job and no work was done by you, right?

**Comment by ypshenychka** [comment]
@blackout314 Why then there is no associated PR where you're creating a table?

**Comment by blackout314** [comment]
@ypshenychka 
https://i.imgur.com/w9Ejgit.png

**Comment by ypshenychka** [comment]
@blackout314 According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>Ticket must have references to all pull requests where the problem was actually fixed

Please confirm next time you will reference the issue in Pull Request so that is is visible here.

**Comment by blackout314** [comment]
@ypshenychka mmm ok, sorry

**Comment by ypshenychka** [comment]
@blackout314 Thank you.

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @blackout314[/z](https://www.0crat.com/u/blackout314)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
