### ISSUE TITLE
wallet - specify the age of the wallet

### ISSUE THREAD

**Issue by oltdaniel** [zold-io/zold.github.io#14]
If there is none or a single transaction, the age is 0.
Else it is the hours between the latest and oldest transaction.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@oltdaniel[/z](https://www.0crat.com/u/oltdaniel) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZUFVA8H) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@oltdaniel is it a bug in the White Paper? If so, please submit it to: https://github.com/zold-io/papers

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zold-io/zold.github.io#14` is not assigned, can't get performer
