### ISSUE TITLE
.rultor.yml is broken

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold.github.io#17]
see #7

We are still using `build.sh`. Moreover, version `1.0.0` is hardcoded everywhere in the code. This is wrong. Instead, we should hardcode `0.0.0` and replace it with the real version, like it's done here, for example: https://github.com/zold-io/zold/blob/master/.rultor.yml#L13-L15

Also, let's move our deployment code from `deploy` to `release` section in `.rultor.yml`

**Comment by yegor256** [comment]
@0crat assign  @blackout314

**Comment by 0crat** [comment]
> @0crat assign @blackout314 ([here](https://github.com/zold-io/zold.github.io/issues/17#issuecomment-394996481))

@yegor256 The job [#17](https://github.com/zold-io/zold.github.io/issues/17) assigned to @blackout314[/z](https://www.0crat.com/u/blackout314), here is [why](https://www.0crat.com/footprint/CAZUFVA8H/1570904494); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by blackout314** [comment]
@yegor256 i add dynamic replace of "@@VERSION" and we dont need "SNAPSHOT" style task

**Comment by 0crat** [comment]
@blackout314[/z](https://www.0crat.com/u/blackout314) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by yegor256** [comment]
@blackout314 thanks

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @blackout314[/z](https://www.0crat.com/u/blackout314), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#17](https://github.com/zold-io/zold.github.io/issues/17) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @blackout314[/z](https://www.0crat.com/u/blackout314)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by blackout314** [comment]
@ypshenychka 👍
