### ISSUE TITLE
map - show error messages on the screen

### ISSUE THREAD

**Issue by oltdaniel** [zold-io/zold.github.io#19]
Currently, the user cannot see if the error is on his side or on the node side. We should display some messages on the screen.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@oltdaniel[/z](https://www.0crat.com/u/oltdaniel) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZUFVA8H) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job [#19](https://github.com/zold-io/zold.github.io/issues/19) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @oltdaniel[/z](https://www.0crat.com/u/oltdaniel)

**Comment by 0crat** [comment]
The job [#19](https://github.com/zold-io/zold.github.io/issues/19) assigned to @blackout314[/z](https://www.0crat.com/u/blackout314), here is [why](https://www.0crat.com/footprint/CAZUFVA8H/1682155997); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by blackout314** [comment]
@oltdaniel isnt clear, what message mean
please give me example

**Comment by oltdaniel** [comment]
@blackout314 Error messages like connection error or timeouts should be displayed.

**Comment by 0crat** [comment]
@blackout314[/z](https://www.0crat.com/u/blackout314) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @blackout314[/z](https://www.0crat.com/u/blackout314) resigned from [#19](https://github.com/zold-io/zold.github.io/issues/19), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @blackout314[/z](https://www.0crat.com/u/blackout314)

**Comment by 0crat** [comment]
Job `gh:zold-io/zold.github.io#19` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#19](https://github.com/zold-io/zold.github.io/issues/19) is now out of scope
