### ISSUE TITLE
explain the distribution strategy

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold.github.io#2]
Let's explain ZLD distribution strategy.

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#2](https://github.com/zold-io/zold.github.io/issues/2); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@rultor deploy

**Comment by 0crat** [comment]
The job [#2](https://github.com/zold-io/zold.github.io/issues/2) is now out of scope
