### ISSUE TITLE
/ledger.html

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold.github.io#27]
Let's create a new HTML page `/ledger.html`. It will get the HTTP query param `wallet`, download the wallet from `b1.zold.io/wallet/ID` and list all transactions in HTML table. Then, the user will click any wallet ID (the beneficiary) and just to a new page `/ledger.html?wallet=...` and will see its ledger. There should be a `back` button too.

Thus, this page will let us go through the entire ledger of the system, jumping from wallet to wallet.

**Comment by 0crat** [comment]
Job [#27](https://github.com/zold-io/zold.github.io/issues/27) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#27](https://github.com/zold-io/zold.github.io/issues/27) assigned to @blackout314[/z](https://www.0crat.com/u/blackout314), here is [why](https://www.0crat.com/footprint/CAZUFVA8H/1782153722); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by blackout314** [comment]
@yegor256 remove me from this task

**Comment by yegor256** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zold-io/zold.github.io/issues/27#issuecomment-401265007))

@yegor256 The user @blackout314[/z](https://www.0crat.com/u/blackout314) resigned from [#27](https://github.com/zold-io/zold.github.io/issues/27), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
The job [#27](https://github.com/zold-io/zold.github.io/issues/27) assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/CAZUFVA8H/bf923ae3-4836-4619-81f7-6569b78afa98); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by amihaiemil** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zold-io/zold.github.io/issues/27#issuecomment-454028456))

@amihaiemil The user @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) resigned from [#27](https://github.com/zold-io/zold.github.io/issues/27), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#27](https://github.com/zold-io/zold.github.io/issues/27); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#27](https://github.com/zold-io/zold.github.io/issues/27); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
Job `gh:zold-io/zold.github.io#27` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#27](https://github.com/zold-io/zold.github.io/issues/27) is now out of scope
