### ISSUE TITLE
mark expired scores

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold.github.io#28]
Sometimes a score may be expired. There is a flag in JSON: `score/expired`. If it is set to `true`, let's mark it somehow in the table: `/map.html`. Maybe with `text-decoration:line-through`

**Comment by 0crat** [comment]
Job [#28](https://github.com/zold-io/zold.github.io/issues/28) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Job `gh:zold-io/zold.github.io#28` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#28](https://github.com/zold-io/zold.github.io/issues/28) is now out of scope
