### ISSUE TITLE
sass-lint

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold.github.io#34]
Let's add sass-lint to the build: https://www.npmjs.com/package/sass-lint

**Comment by 0crat** [comment]
Job [#34](https://github.com/zold-io/zold.github.io/issues/34) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by blackout314** [comment]
@yegor256 i can do this

**Comment by yegor256** [comment]
@0crat assign @blackout314

**Comment by 0crat** [comment]
> @0crat assign @blackout314  ([here](https://github.com/zold-io/zold.github.io/issues/34#issuecomment-397687146))

@yegor256 The job [#34](https://github.com/zold-io/zold.github.io/issues/34) assigned to @blackout314[/z](https://www.0crat.com/u/blackout314), here is [why](https://www.0crat.com/footprint/CAZUFVA8H/1661728574); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by blackout314** [comment]
@yegor256 this task --> closed

**Comment by yegor256** [comment]
@blackout314 thanks!

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.0`

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @blackout314[/z](https://www.0crat.com/u/blackout314), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#34](https://github.com/zold-io/zold.github.io/issues/34) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @blackout314[/z](https://www.0crat.com/u/blackout314)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
