### ISSUE TITLE
travis need npm start

### ISSUE THREAD

**Issue by blackout314** [zold-io/zold.github.io#37]
we miss `npm start` for travis

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@blackout314 it's clean now, thanks: https://travis-ci.org/zold-io/zold.github.io

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zold-io/zold.github.io#37` is not assigned, can't get performer

**Comment by blackout314** [comment]
@yegor256 great 👯
