### ISSUE TITLE
show error when the header of the map can't load

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold.github.io#42]
Let's show something when we can't load the header. Now we are just staying quiet.

**Comment by 0crat** [comment]
Job [#42](https://github.com/zold-io/zold.github.io/issues/42) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Job `gh:zold-io/zold.github.io#42` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#42](https://github.com/zold-io/zold.github.io/issues/42) is now out of scope
