### ISSUE TITLE
security vulnerability

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold.github.io#43]
GitHub shows this:

<img width="1025" alt="screen shot 2018-06-18 at 1 54 55 pm" src="https://user-images.githubusercontent.com/526301/41532334-42cf8d2c-72ff-11e8-8cc5-2590b952fc13.png">

Let's investigate and get rid of this.

**Comment by 0crat** [comment]
Job [#43](https://github.com/zold-io/zold.github.io/issues/43) is now in scope, role is `DEV`

**Comment by yegor256** [comment]
@blackout314 here:

<img width="781" alt="screen shot 2018-06-18 at 1 55 55 pm" src="https://user-images.githubusercontent.com/526301/41532366-624c8196-72ff-11e8-8628-b09327dd8dfe.png">

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@0crat assign @blackout314

**Comment by 0crat** [comment]
> @0crat assign @blackout314  ([here](https://github.com/zold-io/zold.github.io/issues/43#issuecomment-398017178))

@yegor256 The job [#43](https://github.com/zold-io/zold.github.io/issues/43) assigned to @blackout314[/z](https://www.0crat.com/u/blackout314), here is [why](https://www.0crat.com/footprint/CAZUFVA8H/1691059413); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by blackout314** [comment]
@yegor256 i fix this asap

**Comment by blackout314** [comment]
@yegor256 
little problem

```
├─┬ grunt-sass@2.0.0
│ └─┬ node-sass@4.9.0
│   └─┬ request@2.79.0
│     └─┬ hawk@3.1.3
│       ├─┬ boom@2.10.1
│       │ └── hoek@2.16.3  deduped
│       ├── hoek@2.16.3
│       └─┬ sntp@1.0.9
│         └── hoek@2.16.3  deduped
```

node-sass >> https://github.com/sass/node-sass/releases use this old version of hoek

**Comment by blackout314** [comment]
@yegor256 done it

**Comment by blackout314** [comment]
@yegor256 you can close this

**Comment by yegor256** [comment]
@blackout314 thanks

**Comment by 0crat** [comment]
Quality review for [#43](https://github.com/zold-io/zold.github.io/issues/43) already exists

**Comment by 0crat** [comment]
The job [#43](https://github.com/zold-io/zold.github.io/issues/43) is now out of scope

**Comment by ypshenychka** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zold-io/zold.github.io/issues/43#issuecomment-428504859))

@ypshenychka This is what I know about this job in [CAZUFVA8H](https://www.0crat.com/p/CAZUFVA8H), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#43](https://github.com/zold-io/zold.github.io/issues/43) is not in scope
  * The job is waiting quality review verdict by @ypshenychka[/z](https://www.0crat.com/u/ypshenychka) for 4mon
  * @blackout314[/z](https://www.0crat.com/u/blackout314) will receive 30 minutes after quality review
  * Job [footprint](https://www.0crat.com/footprint/CAZUFVA8H?q=%7Bjob%3A%27gh%3Azold-io%2Fzold.github.io%2343%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by ypshenychka** [comment]
@blackout314 According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>All commit messages have links to issues

Your commits do not contain link to this issue. Please confirm you'll try to follow this rule next time.

**Comment by blackout314** [comment]
@ypshenychka next time i'll try to follow this rule. sorry

**Comment by ypshenychka** [comment]
@blackout314 thank you

**Comment by ypshenychka** [comment]
@0crat quality acceptable
