### ISSUE TITLE
Error in browser console on map.html

### ISSUE THREAD

**Issue by alex-semenyuk** [zold-io/zold.github.io#48]
Got the following message in browser console on map.html:

> Failed to load http://www.geoplugin.net/json.gp?ip=.....: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.zold.io' is therefore not allowed access. The response had HTTP status code 403.

Suppose that need to use  CORS Anywhere how it is described here https://ourcodeworld.com/articles/read/73/how-to-bypass-access-control-allow-origin-error-with-xmlhttprequest-jquery-ajax-

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@alex-semenyuk[/z](https://www.0crat.com/u/alex-semenyuk) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZUFVA8H) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job `gh:zold-io/zold.github.io#48` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
