### ISSUE TITLE
/balance.html

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold.github.io#50]
Let's create a new web page `/balance.hml` which will be similar to https://ethereum.org/ether. You enter your wallet ID and it fetches the wallet from a number or nodes and shows the balance.

**Comment by 0crat** [comment]
Job [#50](https://github.com/zold-io/zold.github.io/issues/50) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#50](https://github.com/zold-io/zold.github.io/issues/50); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
implemented in `/ledger.html`

**Comment by 0crat** [comment]
Job `gh:zold-io/zold.github.io#50` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#50](https://github.com/zold-io/zold.github.io/issues/50) is now out of scope
