### ISSUE TITLE
trivial - zold logo in map not visible

### ISSUE THREAD

**Issue by blackout314** [zold-io/zold.github.io#55]
move logo

![](https://i.imgur.com/NuGMPqs.png)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@blackout314 we don't have the list there anymore

**Comment by 0crat** [comment]
Job `gh:zold-io/zold.github.io#55` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
