### ISSUE TITLE
Grunt instead of build.sh

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold.github.io#7]
Let's use Grunt to build the product. Now we have `build.sh`, which is just a temporary implementation.

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` is banned at [#7](https://github.com/zold-io/zold.github.io/issues/7); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@0crat assign @blackout314

**Comment by 0crat** [comment]
> @0crat assign @blackout314 ([here](https://github.com/zold-io/zold.github.io/issues/7#issuecomment-394714887))

@yegor256 The job [#7](https://github.com/zold-io/zold.github.io/issues/7) assigned to @blackout314[/z](https://www.0crat.com/u/blackout314), here is [why](https://www.0crat.com/footprint/CAZUFVA8H/1561354023); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by blackout314** [comment]
how i close this?

**Comment by yegor256** [comment]
@blackout314 you ask the ticket reporter to close

**Comment by yegor256** [comment]
@rultor deploy

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @blackout314[/z](https://www.0crat.com/u/blackout314), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#7](https://github.com/zold-io/zold.github.io/issues/7) is now out of scope

**Comment by ypshenychka** [comment]
@blackout314 According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>Messages in a job [always](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html#4-avoid-noiseaddress-your-comments) start with a name of a user they are addressed to.

Please correct your [message](https://github.com/zold-io/zold.github.io/issues/7#issuecomment-394977065) by indicating an addressee in the beginning.

**Comment by ypshenychka** [comment]
@blackout314 According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>Ticket must have references to all pull requests where the problem was actually fixed

Please reference the corresponding PR in this issue, so everyone's aware where the problem was solved.

**Comment by blackout314** [comment]
@ypshenychka the PR replace build.sh with FE building of source for deploy artifact

**Comment by ypshenychka** [comment]
@blackout314 Thanks.

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @blackout314[/z](https://www.0crat.com/u/blackout314)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
