### ISSUE TITLE
more links

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold.github.io#74]

**Comment by yegor256** [comment]
@rultor release, tag is `0.6.6`

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@ff4e4492-afa3-49e7-b2e6-def21277e93d, thread: pool-730-thread-1
java.lang.NumberFormatException[65] java.lang.NumberFormatException: For input string: "2018-08-02T14:01:57.73Z"
```

[0.28.5](https://github.com/zerocracy/farm): Issue: zold-io/zold.github.io#74, Action: `closed`
