### ISSUE TITLE
show actual NScore

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold.github.io#76]

**Comment by yegor256** [comment]
@rultor release, tag is `0.6.8`

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@25fbab20-c312-42db-aced-b573bac3c501, thread: pool-19-thread-1
java.lang.NumberFormatException[65] java.lang.NumberFormatException: For input string: "2018-08-03T05:44:34.785Z"
```

[0.28.14](https://github.com/zerocracy/farm): Issue: zold-io/zold.github.io#76, Action: `closed`

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zold-io/zold.github.io/issues/76#issuecomment-410455875))

@g4s8 This is what I know about this job in [CAZUFVA8H](https://www.0crat.com/p/CAZUFVA8H), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#76](https://github.com/zold-io/zold.github.io/issues/76) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/CAZUFVA8H?q=%7Bjob%3A%27gh%3Azold-io%2Fzold.github.io%2376%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)
