### ISSUE TITLE
hide IP if it's host address

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold.github.io#77]

**Comment by yegor256** [comment]
@rultor release, tag is `0.6.9`

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@7bda313d-71fb-41d0-8d6f-eda5801ea74b, thread: pool-349-thread-1
java.lang.NumberFormatException[65] java.lang.NumberFormatException: For input string: "2018-08-03T18:19:54.406Z"
```

[0.28.15](https://github.com/zerocracy/farm): Issue: zold-io/zold.github.io#77, Action: `closed`
