### ISSUE TITLE
colorizejs

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold.github.io#81]
Let's use it from here: https://github.com/yegor256/colorizejs

**Comment by yegor256** [comment]
@rultor release, tag is `0.7.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.7.2`

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zold-io/zold.github.io#81` is not assigned, can't get performer
