### ISSUE TITLE
jslint

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold.github.io#87]
Let's add jslint to the build and make sure the build doesn't pass when jslint reports any errors or warnings.

**Comment by 0crat** [comment]
Job [#87](https://github.com/zold-io/zold.github.io/issues/87) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
done

**Comment by 0crat** [comment]
Job `gh:zold-io/zold.github.io#87` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#87](https://github.com/zold-io/zold.github.io/issues/87) is now out of scope
