### ISSUE TITLE
HTTP requests lead to HTTPS for some reason

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold.github.io#93]

**Comment by yegor256** [comment]
@rultor release, tag is `0.10.4`

**Comment by 0crat** [comment]
Job `gh:zold-io/zold.github.io#93` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by yegor256** [comment]
@rultor release, tag is `0.10.4`
